version: '3'

services:

  rest-server:
    build:
      context: ./webserver
    ports:
      - 5000:5000
    env_file:
      ./credentials.env
    volumes:
      - ./webserver/src:/app
    container_name: 140restserver

  mysql-db:
    image: mysql:latest
    restart: always
    env_file:
      ./credentials.env
    ports:
      - 3306:3306                     # external port : internal mysql port
    volumes:
      - ./persist_db:/var/lib/mysql   # persist when container is stopped!
    container_name: 140restdb

volumes:
  persist_db: